# Generated by Django 2.2.15 on 2020-08-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200825_0513"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key1",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key1",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key2",
            field=models.OneToOneField(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key2",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key3",
            field=models.ForeignKey(
                blank=True,
                default=3,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key3",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key4",
            field=models.ForeignKey(
                blank=True,
                default=4,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key4",
                to="home.CustomText",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
