# Generated by Django 2.2.15 on 2020-08-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200825_0513"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="key1",),
        migrations.RemoveField(model_name="user", name="key2",),
        migrations.RemoveField(model_name="user", name="key3",),
        migrations.RemoveField(model_name="user", name="key4",),
    ]
