# Generated by Django 2.2.15 on 2020-08-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="key1",
            field=models.ForeignKey(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customtext_key1",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="key2",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customtext_key2",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="new",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customtext_new",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="test",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customtext_test",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="tests",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customtext_tests",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customtext_user",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="key1",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="homepage_key1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="key2",
            field=models.ForeignKey(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="homepage_key2",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="key3",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="homepage_key3",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="key4",
            field=models.OneToOneField(
                blank=True,
                default=4,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="homepage_key4",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
